/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 06-Sep-2017 12:49:28 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `hangouts` CASCADE
;

/* Create Tables */

CREATE TABLE `hangouts`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(512) NULL,
	`image` TEXT NULL,
	`url` VARCHAR(512) NULL,
	`description` TEXT NULL,
	`id_role` INT NULL,
	`activation_date` TIMESTAMP NULL,
	CONSTRAINT `PK_hangouts` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Agregar los treamings de aprende y enseña'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `hangouts` 
 ADD INDEX `IXFK_hangouts_role` (`id_role` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `hangouts` 
 ADD CONSTRAINT `FK_hangouts_role`
	FOREIGN KEY (`id_role`) REFERENCES `role` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
