/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 04-feb.-2017 12:53:11 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `institution` CASCADE
;

/* Create Tables */

CREATE TABLE `institution`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL,
	`nit` VARCHAR(50) NULL,
	`address` VARCHAR(255) NULL,
	`website` VARCHAR(255) NULL,
	`email` VARCHAR(255) NULL,
	`second_email` VARCHAR(255) NULL,
	`phone` VARCHAR(255) NULL,
	`head_sector` BOOL NULL,
	`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`designation_act` VARCHAR(255) NULL,
	`legalrep_name` VARCHAR(50) NULL,
	`legalrep_secondname` VARCHAR(50) NULL,
	`legalrep_lastname` VARCHAR(50) NULL,
	`legalrep_secondlastname` VARCHAR(50) NULL,
	`leaglrep_document` VARCHAR(50) NULL,
	`legalrep_typedoc` INT NULL,
	`legalrep_email` VARCHAR(255) NULL,
	`id_city` INT NULL,
	`id_region` INT NULL,
	`id_user_creator` INT NULL COMMENT 'Usuario Responsable de la Institución',
	CONSTRAINT `PK_institution` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Se refiere a un punto en espacial'

;

/* Create Foreign Key Constraints */

ALTER TABLE `institution` 
 ADD CONSTRAINT `FK_Institution_City`
	FOREIGN KEY (`id_city`) REFERENCES `city` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `institution` 
 ADD CONSTRAINT `FK_institution_region`
	FOREIGN KEY (`id_region`) REFERENCES `region` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `institution` 
 ADD CONSTRAINT `FK_institution_user`
	FOREIGN KEY (`id_user_creator`) REFERENCES `user` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
