/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 30-Oct-2017 11:55:22 AM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `motivename` CASCADE
;

DROP TABLE IF EXISTS `motives` CASCADE
;

/* Create Tables */

CREATE TABLE `motivename`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL,
	CONSTRAINT `PK_motivetype` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `motives`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` INT NULL,
	`points` INT NULL,
	`description` TEXT NULL,
	`id_category` INT NULL,
	`level` INT NULL,
	`id_role` INT NULL,
	`public` TINYINT NOT NULL DEFAULT 0,
	CONSTRAINT `PK_motives` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Posibles motivos para agregar puntos'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `motives` 
 ADD INDEX `IXFK_motives_category` (`id_category` ASC)
;

ALTER TABLE `motives` 
 ADD INDEX `IXFK_motives_motivetype` (`name` ASC)
;

ALTER TABLE `motives` 
 ADD INDEX `IXFK_motives_role` (`id_role` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `motives` 
 ADD CONSTRAINT `FK_motives_category`
	FOREIGN KEY (`id_category`) REFERENCES `category` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `motives` 
 ADD CONSTRAINT `FK_motives_motivetype`
	FOREIGN KEY (`name`) REFERENCES `motivename` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `motives` 
 ADD CONSTRAINT `FK_motives_role`
	FOREIGN KEY (`id_role`) REFERENCES `role` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
INSERT INTO `stamp_test`.`motivename` (`id`, `name`) VALUES ('1', 'Aceptar Requisito');
INSERT INTO `stamp_test`.`motivename` (`id`, `name`) VALUES ('2', 'Calificar Requisito');
INSERT INTO `stamp_test`.`motivename` (`id`, `name`) VALUES ('3', 'Participar en Aprende y Enseña');
INSERT INTO `stamp_test`.`motivename` (`id`, `name`) VALUES ('4', 'Aceptar Voluntaria');
INSERT INTO `stamp_test`.`motivename` (`id`, `name`) VALUES ('5', 'Eventos Especiales');
INSERT INTO `stamp_test`.`motivename` (`id`, `name`) VALUES ('6', 'No evaluar');
INSERT INTO `stamp_test`.`motivename` (`id`, `name`) VALUES ('7', 'Rechazar Requisit');
INSERT INTO `stamp_test`.`motivename` (`id`, `name`) VALUES ('8', 'Postular Servicio');
INSERT INTO `stamp_test`.`motivename` (`id`, `name`) VALUES ('9', 'Postulación Rechazada');
INSERT INTO `stamp_test`.`motivename` (`id`, `name`) VALUES ('10', 'Cumplimiento Sello');
INSERT INTO `stamp_test`.`motivename` (`id`, `name`) VALUES ('11', 'Incumplimiento Sello');
