/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * banner
 * [
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "title",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "text",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "background",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "position",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "active",
		"Type": "tinyint(4)",
		"Null": "NO",
		"Key": "",
		"Default": "1",
		"Extra": ""
	},
	{
		"Field": "timestamp",
		"Type": "timestamp",
		"Null": "NO",
		"Key": "",
		"Default": "1",
		"Extra": ""
	}
]
 * DMT 2017
 * GENERATED: 19 / 9 / 2017 - 11:4:37
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Banner = function () {
	var params = [{
		table:'banner',
		fields :[
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "title",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "text",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "background",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "position",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "active",
		"Type": "tinyint(4)",
		"Null": "NO",
		"Key": "",
		"Default": "1",
		"Extra": ""
	},
	{
		"Field": "timestamp",
		"Type": "timestamp",
		"Null": "NO",
		"Key": "",
		"Default": "CURRENT_TIMESTAMP",
		"Extra": ""
	}
],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Banner, BaseModel)
module.exports = Banner