/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * city
 * [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"name","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"code","Type":"varchar(50)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"latitude","Type":"double(10,2)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"longitude","Type":"double(10,2)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"id_region","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""}]
 * DMT 2017
 * GENERATED: 5 / 9 / 2017 - 7:38:21
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var City = function () {
	var params = [{
		table:'city',
		fields :[{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"name","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"code","Type":"varchar(50)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"latitude","Type":"double(10,2)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"longitude","Type":"double(10,2)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"id_region","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""}],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(City, BaseModel)
module.exports = City