/**  * ENTITY AUTO_GENERATED BY DMT-GENERATOR
 * {{ENTITY_NAME}}
 * DMT 2017
 * GENERATED: 5 / 9 / 2017 - 7:39:27
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Region = function () {
	var params = [{"table":"region","relations":[{"type":"1-1","entity":"country","name":"country","leftKey":"id_country","foreign_name":"name"},{"type":"1-1","entity":"city","name":"capital","leftKey":"id_capital","foreign_name":"name"}],"entity":"region","model":"entity"}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Region, BaseModel)
module.exports = Region