/**  * ENTITY AUTO_GENERATED BY DMT-GENERATOR
 * {{ENTITY_NAME}}
 * DMT 2017
 * GENERATED: 5 / 9 / 2017 - 7:39:27
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Banner = function () {
	var params = [{"table":"banner","relations":[{"type":"1-1","entity":"type_banner","name":"type","leftKey":"id_type_banner","foreign_name":"name"}],"entity":"banner","model":"entity"}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Banner, BaseModel)
module.exports = Banner