/**  * ENTITY AUTO_GENERATED BY DMT-GENERATOR
 * {{ENTITY_NAME}}
 * DMT 2017
 * GENERATED: 20 / 11 / 2017 - 15:37:42
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Country = function () {
	var params = [{
	"table": "country",
	"relations": [
		{
			"type": "1-1",
			"entity": "city",
			"name": "capital",
			"leftKey": "id_capital",
			"foreign_name": "name"
		}
	],
	"entity": "country",
	"model": "entity"
}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Country, BaseModel)
module.exports = Country