/**  * ENTITY AUTO_GENERATED BY DMT-GENERATOR
 * {{ENTITY_NAME}}
 * DMT 2017
 * GENERATED: 5 / 9 / 2017 - 7:39:27
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Question = function () {
	var params = [{"table":"question","relations":[{"type":"1-1","name":"topic","entity":"questiontopic","leftKey":"id_topic","foreign_name":"name"}],"entity":"question","model":"entity"}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Question, BaseModel)
module.exports = Question