/**  * ENTITY AUTO_GENERATED BY DMT-GENERATOR
 * {{ENTITY_NAME}}
 * DMT 2017
 * GENERATED: 30 / 10 / 2017 - 12:8:21
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Motives = function () {
	var params = [{
	"table": "motives",
	"relations": [
		{
			"type": "1-1",
			"entity": "motivename",
			"name": "name",
			"leftKey": "id_name",
			"foreign_name": "name"
		},
		{
			"type": "1-1",
			"entity": "category",
			"name": "category",
			"leftKey": "id_category",
			"foreign_name": "name"
		},
		{
			"type": "1-1",
			"entity": "role",
			"leftKey": "id_role",
			"name": "role",
			"foreign_name": "name"
		}
	],
	"entity": "motives",
	"model": "entity"
}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Motives, BaseModel)
module.exports = Motives