/**  * ENTITY AUTO_GENERATED BY DMT-GENERATOR
 * {{ENTITY_NAME}}
 * DMT 2017
 * GENERATED: 12 / 9 / 2017 - 17:6:41
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Institution_user = function () {
	var params = [{
	"table": "institution_user",
	"relations": [
		{
			"type": "1-1",
			"entity": "institution",
			"name": "institution",
			"leftKey": "id_institution",
			"foreign_name": "name"
		},
		{
			"type": "1-1",
			"entity": "user",
			"name": "user",
			"leftKey": "id_user",
			"foreign_name": "email"
		}
	],
	"entity": "institution_user",
	"model": "entity"
}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Institution_user, BaseModel)
module.exports = Institution_user