/**  * ENTITY AUTO_GENERATED BY DMT-GENERATOR
 * {{ENTITY_NAME}}
 * DMT 2017
 * GENERATED: 27 / 9 / 2017 - 19:43:23
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Role = function () {
	var params = [{
	"table": "role",
	"relations": [
		{
			"type": "n-n",
			"entity": "permission",
			"name": "permissions",
			"intermediate": {
				"entity": "permission_role",
				"leftKey": "id_role",
				"rightKey": "id_permission"
			}
		}
	],
	"entity": "role",
	"model": "entity"
}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Role, BaseModel)
module.exports = Role