/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * institution_user
 * [{"Field":"id_institution","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"id_user","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"role","Type":"varchar(50)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"admin","Type":"tinyint(1)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"certificate","Type":"text","Null":"YES","Key":"","Default":null,"Extra":""}]
 * DMT 2017
 * GENERATED: 5 / 9 / 2017 - 7:38:21
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Institution_user = function () {
	var params = [{
		table:'institution_user',
		fields :[{"Field":"id_institution","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"id_user","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"role","Type":"varchar(50)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"admin","Type":"tinyint(1)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"certificate","Type":"text","Null":"YES","Key":"","Default":null,"Extra":""}],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Institution_user, BaseModel)
module.exports = Institution_user