/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * institution
 * [
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "name",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "nit",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "address",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "website",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "email",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "phone",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "extension_phone",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "head_sector",
		"Type": "tinyint(1)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "timestamp",
		"Type": "timestamp",
		"Null": "NO",
		"Key": "",
		"Default": "CURRENT_TIMESTAMP",
		"Extra": ""
	},
	{
		"Field": "designation_act",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_name",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_secondname",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_lastname",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_secondlastname",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_document",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_typedoc",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_email",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_phone",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_mobile",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_city",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_region",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_country",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_user_creator",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_institution_type",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "active",
		"Type": "tinyint(4)",
		"Null": "NO",
		"Key": "",
		"Default": "1",
		"Extra": ""
	}
]
 * DMT 2017
 * GENERATED: 15 / 11 / 2017 - 16:29:51
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Institution = function () {
	var params = [{
		table:'institution',
		fields :[
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "name",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "nit",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "address",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "website",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "email",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "phone",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "extension_phone",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "head_sector",
		"Type": "tinyint(1)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "timestamp",
		"Type": "timestamp",
		"Null": "NO",
		"Key": "",
		"Default": "CURRENT_TIMESTAMP",
		"Extra": ""
	},
	{
		"Field": "designation_act",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_name",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_secondname",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_lastname",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_secondlastname",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_document",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_typedoc",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_email",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_phone",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legalrep_mobile",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_city",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_region",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_country",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_user_creator",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_institution_type",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "active",
		"Type": "tinyint(4)",
		"Null": "NO",
		"Key": "",
		"Default": "1",
		"Extra": ""
	}
],
		model:'mysql'
	}]
	BaseModel.apply(this, params)

	/**
	 * Get Top entities, supports
	 * {
				limit: params.limit
				page: params.page
			}
	 */
	this.getUser = function(id){
		let q = `SELECT u.* FROM user u 
		JOIN institution_user u_i on u_i.id_user = u.id
		JOIN institution i on i.id = u_i.id_institution
		WHERE i.id = '${id}'`
		return this.customQuery(q)
	}
	
	return this
};
util.inherits(Institution, BaseModel)
module.exports = Institution