/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * motives
 * [
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "id_name",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "points",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "description",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_category",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "level",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_role",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "public",
		"Type": "tinyint(4)",
		"Null": "NO",
		"Key": "",
		"Default": "0",
		"Extra": ""
	}
]
 * DMT 2017
 * GENERATED: 21 / 11 / 2017 - 9:4:37
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Motives = function () {
	var params = [{
		table:'motives',
		fields :[
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "id_name",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "points",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "description",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_category",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "level",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "id_role",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "public",
		"Type": "tinyint(4)",
		"Null": "NO",
		"Key": "",
		"Default": "0",
		"Extra": ""
	}
],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Motives, BaseModel)
module.exports = Motives