/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * motivename
 * [
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "name",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	}
]
 * DMT 2017
 * GENERATED: 30 / 10 / 2017 - 12:8:21
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Motivename = function () {
	var params = [{
		table:'motivename',
		fields :[
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "name",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	}
],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Motivename, BaseModel)
module.exports = Motivename