/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * question
 * [
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "id_topic",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "level",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "text",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "criteria",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "evidence",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legal_support",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "help",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "active",
		"Type": "tinyint(4)",
		"Null": "NO",
		"Key": "",
		"Default": "1",
		"Extra": ""
	}
]
 * DMT 2017
 * GENERATED: 13 / 11 / 2017 - 13:10:37
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Question = function () {
	var params = [{
		table:'question',
		fields :[
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "id_topic",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "MUL",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "level",
		"Type": "int(11)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "text",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "criteria",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "evidence",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "legal_support",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "help",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "active",
		"Type": "tinyint(4)",
		"Null": "NO",
		"Key": "",
		"Default": "1",
		"Extra": ""
	}
],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Question, BaseModel)
module.exports = Question