/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * request_status
 * [
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "name",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "duration",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "",
		"Default": "10",
		"Extra": ""
	},
	{
		"Field": "pre_end",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "",
		"Default": "2",
		"Extra": ""
	},
	{
		"Field": "alert",
		"Type": "tinyint(1)",
		"Null": "NO",
		"Key": "",
		"Default": "1",
		"Extra": ""
	},
	{
		"Field": "description",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	}
]
 * DMT 2017
 * GENERATED: 21 / 11 / 2017 - 10:50:12
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Request_status = function () {
	var params = [{
		table:'request_status',
		fields :[
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "name",
		"Type": "varchar(50)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "duration",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "",
		"Default": "10",
		"Extra": ""
	},
	{
		"Field": "pre_end",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "",
		"Default": "2",
		"Extra": ""
	},
	{
		"Field": "alert",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "",
		"Default": "1",
		"Extra": ""
	},
	{
		"Field": "description",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	}
],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Request_status, BaseModel)
module.exports = Request_status