/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * usertype
 * [
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "name",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "description",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "active",
		"Type": "tinyint(4)",
		"Null": "NO",
		"Key": "",
		"Default": "1",
		"Extra": ""
	}
]
 * DMT 2017
 * GENERATED: 6 / 11 / 2017 - 0:45:52
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Usertype = function () {
	var params = [{
		table:'usertype',
		fields :[
	{
		"Field": "id",
		"Type": "int(11)",
		"Null": "NO",
		"Key": "PRI",
		"Default": null,
		"Extra": "auto_increment"
	},
	{
		"Field": "name",
		"Type": "varchar(255)",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "description",
		"Type": "text",
		"Null": "YES",
		"Key": "",
		"Default": null,
		"Extra": ""
	},
	{
		"Field": "active",
		"Type": "tinyint(4)",
		"Null": "NO",
		"Key": "",
		"Default": "1",
		"Extra": ""
	}
],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Usertype, BaseModel)
module.exports = Usertype